# Generated by Django 3.2.7 on 2022-02-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_alter_after10_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result12arts',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='result12arts',
            name='question',
        ),
        migrations.RemoveField(
            model_name='result12arts',
            name='username',
        ),
        migrations.AddField(
            model_name='after12arts',
            name='correct_answer',
            field=models.CharField(default=' ', max_length=120),
        ),
        migrations.AddField(
            model_name='after12arts',
            name='op1',
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='after12arts',
            name='op2',
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='after12arts',
            name='op3',
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='after12arts',
            name='op4',
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='after12arts',
            name='question_type',
            field=models.CharField(default=' ', max_length=120),
        ),
        migrations.AlterField(
            model_name='after12arts',
            name='question',
            field=models.CharField(max_length=900, unique=True),
        ),
    ]
