# Generated by Django 3.2.7 on 2022-02-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_auto_20220225_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result12arts',
            name='answer',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='result12arts',
            name='question',
            field=models.CharField(default='', max_length=255),
        ),
    ]
