# Generated by Django 3.2.7 on 2022-02-25 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_auto_20220225_1324'),
    ]

    operations = [
        migrations.DeleteModel(
            name='result12arts',
        ),
    ]
