# Generated by Django 3.2.7 on 2022-02-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_delete_result12arts'),
    ]

    operations = [
        migrations.CreateModel(
            name='result12arts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(blank=True, max_length=254)),
                ('question', models.CharField(default='', max_length=255)),
                ('answer', models.CharField(default='', max_length=255)),
                ('question_type', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
