# Generated by Django 3.2.7 on 2022-02-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_result12arts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result12artsCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('count_ID', models.CharField(max_length=10)),
                ('count_Journalism', models.CharField(max_length=10)),
                ('count_Fashion', models.CharField(max_length=10)),
                ('count_Hotel', models.CharField(default=' ', max_length=10)),
            ],
        ),
    ]
