# Generated by Django 3.2.7 on 2022-04-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_result12artscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='after12commerce',
            name='correct_answer',
            field=models.CharField(default=' ', max_length=120),
        ),
        migrations.AddField(
            model_name='after12commerce',
            name='op1',
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='after12commerce',
            name='op2',
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='after12commerce',
            name='op3',
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='after12commerce',
            name='op4',
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='after12commerce',
            name='question_type',
            field=models.CharField(default=' ', max_length=120),
        ),
        migrations.AddField(
            model_name='after12science',
            name='count_arts',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='after12science',
            name='count_commerce',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='after12science',
            name='count_diploma',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='after12science',
            name='count_science',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='after12science',
            name='username',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
