# Generated by Django 3.2.7 on 2022-07-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_alter_after12commerce_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result12comm',
            name='answer',
            field=models.CharField(default='', max_length=900),
        ),
    ]
