# Generated by Django 3.2.7 on 2022-07-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_alter_result12comm_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result12sci',
            name='answer',
            field=models.CharField(default='', max_length=900),
        ),
    ]
